apiVersion: v1
kind: ServiceAccount 
metadata:
  name: mlflow-sa 
  namespace: mlflow 
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mlflow-deployment 
  namespace: mlflow 
  labels:
    app: mlflow
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: mlflow 
    template:
      metadata:
        labels:
          app: mlflow 
      spec:
        serviceAccountName: mlflow-sa
        containers:
        - name: mlflow
          image: akinolawilson/mlflow:latest
          imagePullPolicy: Always 
          command: ["/bin/bash"]
          args:
            ["mlflow server --host 0.0.0.0 --port 5001 --backend-store-uri sqlite:///meta.db"] # --artifacts-destination s3://my-bucket 
          
          volumeMounts:
          - mountPath: /usr/src/app
            name: pv-data
        volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: pvc-data
                          
            ports:
              - containerPort: 5001



# See https://mlflow.org/docs/latest/tracking/server.html for configuration details 

# --backend-store-uri sqlite:///meta.db creates meta data database locally under current working directory called 'meta/db' 

# --artifacts-destination s3://my-bucket  will use my-bucket as remote storage. MLFLow server will then act as a proxy for accessing the artifacts 
#  W/O specifying this flag, artifacts are store locally under current working directory in folder './mlartifacts'


