kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kf-cluster
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /home/ola/Code/kflow/volume
      containerPath: /data
- role: worker
- role: worker
- role: worker