
# persistent volume claims are a pain to set up locally with kind. need to specify ahead of cluster
# creation what extra mounting paths inside and outside the container will be to be able to use volumes 
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /home/ola/Code/k8s/4pods/data
      containerPath: /usr/src/app/data
---
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: hello-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath: /usr/src/app/data
    path: 
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: hello-data-claim
spec:
  volumeName: hello-data
  acccessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 1Gi 



